CREATE DATABASE QLCHBANCHO
USE [QLCHBANCHO]
GO

CREATE TABLE LOAICHO
(
	MALOAI CHAR(10) NOT NULL,
	TENLOAI NVARCHAR(50)
	CONSTRAINT PK_LOAICHO PRIMARY KEY(MALOAI)
)

CREATE TABLE CHO
(
	MAXACNHAN CHAR(10) NOT NULL,
	TENCHO NVARCHAR(50),
	MALOAI CHAR(10),
	MAU NVARCHAR(10),
	QUOCTICH NVARCHAR(20),
	GIA INT,
	TINHTRANG nvarchar(50),
	CONSTRAINT PK_CHO PRIMARY KEY(MAXACNHAN)
)

ALTER TABLE CHO
ADD  FOREIGN KEY(MALOAI) REFERENCES LOAICHO(MALOAI)

CREATE TABLE CHUCVU
(
	MACHUCVU CHAR(10) NOT NULL,
	TENNV NVARCHAR(50),
	LUONG INT
	CONSTRAINT PK_CHUCVU PRIMARY KEY(MACHUCVU)
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(10) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(10),
	GIOITINH NVARCHAR(5),
	SOCMND INT,
	DIENTHOAINV char(10),
	DIACHI NVARCHAR(50),
	MACHUCVU CHAR(10),
	MANQL CHAR(10)
)

ALTER TABLE NHANVIEN
ADD  FOREIGN KEY(MANQL) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN
ADD  FOREIGN KEY(MACHUCVU) REFERENCES CHUCVU(MACHUCVU)

CREATE TABLE KHACHHANG
(
	MAKH CHAR(10) ,
	TENKH NVARCHAR(50),
	SDTKHACHHANG char(10) ,
	DIACHIKH NVARCHAR(50),
	PRIMARY KEY (MAKH, SDTKHACHHANG)
)
create table BAOHIEM
(
	MABH nchar(10) not null primary key,
	MAXACNHAN CHAR(10),
	NBD datetime, 
	NKT datetime,
)
ALTER TABLE BAOHIEM
ADD  FOREIGN KEY(MAXACNHAN) REFERENCES CHO(MAXACNHAN)
CREATE TABLE HOADONBAN
(
	MAHD CHAR(10) NOT NULL PRIMARY KEY,
	NGAYLAP DATETIME,
	MANV CHAR(10),
	MAKH CHAR(10),
	MAXACNHAN CHAR(10),
	SOLUONGBAN INT,
	TONGTIEN INT,	
)

ALTER TABLE HOADONBAN
ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOADONBAN
ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE CHITIETHOADONBAN
(
	MACTHD CHAR(10) NOT NULL,
	MAHD CHAR(10),
	TENNV NVARCHAR(10),
	MAXACNHAN CHAR(10) NOT NULL,
	SOLUONGBAN INT,
	DONGIABAN INT,
	TONGTIEN INT,
	PRIMARY KEY (MACTHD, MAHD)
)


ALTER TABLE CHITIETHOADONBAN
ADD FOREIGN KEY(MAHD) REFERENCES HOADONBAN(MAHD)

ALTER TABLE CHITIETHOADONBAN
ADD FOREIGN KEY(MAXACNHAN) REFERENCES CHO(MAXACNHAN)

CREATE TABLE TAIKHOANNV
(
	MANV CHAR(10),
	MATKHAU CHAR(10)
	PRIMARY KEY (MANV)
)

ALTER TABLE TAIKHOANNV
ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE QUYEN
(
	MAQUYEN CHAR(10) NOT NULL PRIMARY KEY,
	QUYEN NVARCHAR(20)
)
CREATE TABLE QL_USER
(
	TENDN CHAR(10),
	MATKHAU CHAR(10),
	HOATDONG NVARCHAR(20),
	PRIMARY KEY (TENDN)
)

 CREATE TABLE QL_NHOM_USER
 (
	MANHOM CHAR (10),
	TENNHOM NVARCHAR(50),
	GHICHU NVARCHAR (50),
	PRIMARY KEY (MANHOM)
 )

 CREATE TABLE QL_USER_NHOMUSER
 (
	TENDN CHAR(10),
	MANHOMUSER CHAR (10),
	GHICHU NVARCHAR (50),
	PRIMARY KEY (MANHOMUSER,TENDN)
 )
 ALTER TABLE QL_USER_NHOMUSER
ADD FOREIGN KEY(TENDN) REFERENCES  QL_USER(TENDN)

 CREATE TABLE QL_PHANQUYEN
 (
	MANHOMUSER CHAR(10),
	MAMANHINH CHAR(10),
	COQUYEN BIT,
	PRIMARY KEY (MANHOMUSER,MAMANHINH)
 )
 ALTER TABLE QL_PHANQUYEN
ADD FOREIGN KEY(MAMANHINH) REFERENCES  MANHINH(MAMANHINH)
 
 CREATE TABLE MANHINH
 (
	MAMANHINH CHAR(10),
	TENMANHINH NVARCHAR (50),
	PRIMARY KEY (MAMANHINH)
 )


USE [QLCHBANCHO]
GO
CREATE TABLE NHOMQUYEN
(
	MANV CHAR(10),
	MAQUYEN CHAR(10)
	PRIMARY KEY (MANV, MAQUYEN)
)

ALTER TABLE NHOMQUYEN
ADD FOREIGN KEY(MAQUYEN) REFERENCES QUYEN(MAQUYEN)
ALTER TABLE NHOMQUYEN
ADD FOREIGN KEY(MANV) REFERENCES TAIKHOANNV(MANV)

CREATE TABLE NHACC
(
	MANCC CHAR(10),
	TENNCC NVARCHAR(50),
	SDTNHACC INT ,
	EMAIL CHAR(20),
	DIACHINCC NVARCHAR(50),
	PRIMARY KEY (MANCC)
)

CREATE TABLE DACDIEM
(
	MANCC CHAR(10) PRIMARY KEY,
	MALOAI CHAR(10),
	MAUCHUDAO NVARCHAR(20)
)

ALTER TABLE DACDIEM
ADD FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC)
ALTER TABLE DACDIEM
ADD FOREIGN KEY(MALOAI) REFERENCES LOAICHO(MALOAI)

CREATE TABLE DONDATHANG_NCC
(
	MADH CHAR(10) NOT NULL PRIMARY KEY,
	MACC CHAR(10),
	SOLUONGDAT INT,
	TRATRUOC INT,
	NGAYLAP DATE,
)

ALTER TABLE DONDATHANG_NCC
ADD FOREIGN KEY(MACC) REFERENCES NHACC(MANCC)

CREATE TABLE CT_DONDATHANG_NCC
(
	MADH CHAR(10) NOT NULL,
	MALOAI CHAR(10) NOT NULL,
	TENCHO NVARCHAR(50),
	SOLUONGDAT INT,
	TRATRUOC INT,
	NGAYLAP DATE,
	PRIMARY KEY(MADH,MALOAI)
)

ALTER TABLE CT_DONDATHANG_NCC
ADD FOREIGN KEY(MADH) REFERENCES DONDATHANG_NCC(MADH)
ALTER TABLE CT_DONDATHANG_NCC
ADD FOREIGN KEY(MALOAI) REFERENCES LOAICHO(MALOAI)

CREATE TABLE DONDATHANG_kh
(
	MADH CHAR(10) PRIMARY KEY,
	MAKH CHAR(10),
	TENCHO NVARCHAR(50),
	MAU NVARCHAR(10),
	TONGSLSANPHAM INT,
	TONGTIEN int,
)

ALTER TABLE DONDATHANG_kh
ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

CREATE TABLE CT_DONDATHANG_kh
(
	MADH CHAR(10),
	MAXACNHAN CHAR(10),
	THANHTIEN int,
	PRIMARY KEY (MADH, MAXACNHAN),
)
ALTER TABLE CT_DONDATHANG_kh
ADD FOREIGN KEY(MADH) REFERENCES DONDATHANG_kh(MADH)
ALTER TABLE CT_DONDATHANG_kh
ADD FOREIGN KEY(MAXACNHAN) REFERENCES CHO(MAXACNHAN)

CREATE TABLE PHIEUNHAP
(
	MAPN CHAR(10) NOT NULL PRIMARY KEY,
	MANV CHAR(10),
	MANCC CHAR(10),
	NGAYNHAP DATETIME,
	TONGTIENNHAP int,
	SOTIENCONLAI int,
	NGAYTRA DATETIME
)

ALTER TABLE PHIEUNHAP
ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE PHIEUNHAP
ADD FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC)

CREATE TABLE CHITIETPHIEUNHAP
(
	MACTPN CHAR(10) NOT NULL,
	MAPN CHAR(10),
	MALOAI CHAR(10),
	SOLUONGSP INT,
	GIATIEN int
	PRIMARY KEY(MACTPN)
)
ALTER TABLE CHITIETPHIEUNHAP
ADD FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN)
ALTER TABLE CHITIETPHIEUNHAP
ADD FOREIGN KEY(MAXACNHAN) REFERENCES CHO(MAXACNHAN)

CREATE TABLE LUONG
(
	MACHUCVU CHAR(10) PRIMARY KEY,
	TIENLUONG INT,
	NGAYCAPNHAT DATETIME
)

ALTER TABLE LUONG
ADD FOREIGN KEY(MACHUCVU) REFERENCES CHUCVU(MACHUCVU)

CREATE TABLE SONGAYNGHI
(
	MANV CHAR(10),
	SONGAYNGHI INT,
	TONGTIENPHAT FLOAT
	PRIMARY KEY (MANV)
)

ALTER TABLE SONGAYNGHI
ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

CREATE TABLE THONGKE
(
	MATK CHAR(10),
	MALOAI CHAR(10),
	MANV CHAR(10),
	NGAYTHONGKE DATETIME,
	TONGCHODB INT,
	TONGDOANHTHU INT
	PRIMARY KEY(MATK)

)
ALTER TABLE THONGKE
ADD  FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
CREATE TABLE CHITIETTHONGKE
(
	MATK CHAR(10),
	MALOAI CHAR(10),
	LOAICHODABAN INT,
	GIAGOC int,
	GIABAN int,
	PRIMARY KEY(MATK, MALOAI)
)

ALTER TABLE CHITIETTHONGKE
ADD  FOREIGN KEY(MATK) REFERENCES THONGKE(MATK)
ALTER TABLE CHITIETTHONGKE
ADD  FOREIGN KEY(MALOAI) REFERENCES LOAICHO(MALOAI)

CREATE TABLE MAU
(
	MAMAU NVARCHAR(50) NOT NULL PRIMARY KEY,
	TENMAU NVARCHAR(50),
)



ALTER TABLE CHO
ADD MAMAU NVARCHAR(50)

ALTER TABLE CHO
ADD FOREIGN KEY(MAMAU) REFERENCES MAU(MAMAU)

insert into LOAICHO(MALOAI, TENLOAI) 
values ('CHH',N'Canis familiaris')
insert into LOAICHO(MALOAI, TENLOAI) 
values ('ALK',N'Canis lupus familiaris')
insert into LOAICHO(MALOAI, TENLOAI) 
values ('CBH',N'Canis lupus familiaris')
insert into LOAICHO(MALOAI, TENLOAI) 
values ('CHK',N'Canis lupus familiaris')
insert into LOAICHO(MALOAI, TENLOAI) 
values ('CP',N'Canis lupus familiaris')


insert into CHO(MAXACNHAN, TENCHO, MALOAI, MAU, QUOCTICH,GIA, TINHTRANG) 
values ('CHH1',N'chó chiwawa','CHH', N'trắng',N'Mexico','4500000', N'có sẵn tại cửa hàng')
insert into CHO(MAXACNHAN, TENCHO, MALOAI, MAU, QUOCTICH,GIA, TINHTRANG) 
values ('ALK1',N'chó Alaskan','ALK', N'màu lông chồn và trắng',N'Hoa Kỳ','đặt mua')
insert into CHO(MAXACNHAN, TENCHO, MALOAI, MAU, QUOCTICH,GIA, TINHTRANG) 
values ('BH',N'cún basset hound','CBH', N'đen pha trắng vàng nâu',N'Pháp, Đảo Anh',N'đặt mua')
insert into CHO(MAXACNHAN, TENCHO, MALOAI, MAU, QUOCTICH,GIA, TINHTRANG) 
values ('HK1',N'chó Husky','CHK', N'trắng đen',N'Xibia',N'đặt mua')
insert into CHO(MAXACNHAN, TENCHO, MALOAI, MAU, QUOCTICH,GIA, TINHTRANG) 
values ('CP1',N'chó Pug','CP', N'màu mơ chim',N'Trung Quốc',N'có sẵn tại cửa hàng')


insert into CHUCVU(MACHUCVU, TENNV,LUONG) 
values ('NV',N'Nguyễn Bích Nụ','45000000')

insert into NHANVIEN(MANQL,MANV, TENNV, GIOITINH,MACHUCVU ,SOCMND, DIACHI, DIENTHOAINV) 
values ('QL02',N'NV01',N'Lý Quý Khánh', N'nam','NV','341541184',N'P.Thảo Điền , quận 2','0903212131')

insert into SONGAYNGHI(MANV,SONGAYNGHI, TONGTIENPHAT)
values ('NV01','3','600000')
insert into TAIKHOANNV(MANV,MATKHAU)
values ('NV01', '1234')

insert into NHACC(MANCC, TENNCC,SDTNHACC,EMAIL,DIACHINCC)
values ('TL',N'Thăng Long','0939252524','thanglongbc@gmail.com',N'383 Lê Đức Thọ, phường 17. Quận Gò Vấp, TP.HCM')
insert into NHACC(MANCC, TENNCC,SDTNHACC,EMAIL,DIACHINCC)
values ('AZ',N'AZ Pet','0888083388','azpet@gmail.com',N'59 Văn Cao, Liễu Giai, Ba Đình, Hà Nội')

insert into DACDIEM(MANCC, MALOAI, MAUCHUDAO)
values ('AZ', 'ALK',N'có toàn bộ màu')

insert into DONDATHANG_NCC(MADH, MACC,SOLUONGDAT,TRATRUOC,NGAYLAP)
values ('DALK','AZ','7','75000000','12/07/2019')

ALTER TABLE PHIEUNHAP
ADD SOTIENTRATRUOC_NCC MONEY
---DEAULT---
ALTER TABLE CHITIETHOADONBAN
ADD CONSTRAINT DF_DONGIABAN DEFAULT (0) FOR SOLUONGBAN


ALTER TABLE CHITIETPHIEUNHAP
ADD CONSTRAINT DF_GIATIEN DEFAULT (0) FOR GIATIEN

ALTER TABLE CHO
ADD CONSTRAINT DF_GIA DEFAULT (0) FOR GIA

ALTER TABLE CHUCVU
ADD CONSTRAINT DF_LUONG DEFAULT (0) FOR LUONG

ALTER TABLE CT_DONDATHANG_NCC
ADD CONSTRAINT DF_SOLUONGDAT DEFAULT (0) FOR SOLUONGDAT
ALTER TABLE CT_DONDATHANG_NCC
ADD CONSTRAINT DF_TRATRUOC DEFAULT (0) FOR TRATRUOC
ALTER TABLE CT_DONDATHANG_NCC
ADD CONSTRAINT DF_NGAYLAP DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NGAYLAP

ALTER TABLE DONDATHANG_KH
ADD CONSTRAINT DF_GT DEFAULT (0) FOR TONGTIEN
ALTER TABLE DONDATHANG_KH
ADD CONSTRAINT DF_TONGSP DEFAULT (0) FOR TONGSLSANPHAM

ALTER TABLE DONDATHANG_NCC
ADD TONGTIENTRATRUOC MONEY

ALTER TABLE DONDATHANG_NCC
ADD CONSTRAINT DF_TONGTIENTRATRUOC DEFAULT (0) FOR TONGTIENTRATRUOC
ALTER TABLE DONDATHANG_NCC
ADD CONSTRAINT DF_SOLUONGDAT_DONDATHANG_NCC DEFAULT (0) FOR SOLUONGDAT
ALTER TABLE DONDATHANG_NCC
ADD CONSTRAINT DF_NGAYLAP_DONDATHANG_NCC DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NGAYLAP

ALTER TABLE HOADONBAN
ADD CONSTRAINT DF_TONGTIEN_HOADONBAN DEFAULT (0) FOR TONGTIEN
ALTER TABLE HOADONBAN
ADD CONSTRAINT DF_NGAYLAP_HOADONBAN DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NGAYLAP

ALTER TABLE LUONG
ADD CONSTRAINT DF_TIENLUONG_LUONG DEFAULT (0) FOR TIENLUONG
ALTER TABLE LUONG
ADD CONSTRAINT DF_NGAYCAPNHAT_LUONG DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NGAYCAPNHAT

ALTER TABLE PHIEUNHAP
ADD CONSTRAINT DF_TONGTIENNHAP_PHIEUNHAP DEFAULT (0) FOR TONGTIENNHAP
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT DF_SOTIENCONLAI_PHIEUNHAP DEFAULT (0) FOR SOTIENCONLAI
ALTER TABLE PHIEUNHAP
ADD CONSTRAINT DF_NGAYNHAP_PHIEUNHAP DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NGAYNHAP

ALTER TABLE BAOHIEM
ADD CONSTRAINT DF_NBD DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NBD

ALTER TABLE BAOHIEM
ADD CONSTRAINT DF_NKT DEFAULT (CONVERT(DATE,GETDATE(),111)) FOR NKT
ALTER TABLE SONGAYNGHI
ADD CONSTRAINT DF_SONGAYNGHI_SONGAYNGHI DEFAULT (0) FOR SONGAYNGHI
ALTER TABLE SONGAYNGHI
ADD CONSTRAINT DF_TONGTIENPHAT_SONGAYNGHI DEFAULT (0) FOR TONGTIENPHAT

ALTER TABLE TAIKHOANNV
ADD CONSTRAINT DF_MK_TAIKHOANNV DEFAULT ('123456789') FOR MATKHAU

ALTER TABLE THONGKE
ADD CONSTRAINT DF_TCDB_THONGKE DEFAULT (0) FOR TONGCHODB
ALTER TABLE THONGKE
ADD CONSTRAINT DF_TONGDT_THONGKE DEFAULT (0) FOR TONGDOANHTHU
ALTER TABLE THONGKE
ADD CONSTRAINT DF_NGAYTK_THONGKE DEFAULT (CONVERT(DATE,GETDATE(),120)) FOR NGAYTHONGKE

---TRIGGER---

--RANG BUOC TONG TIEN HOA DON BAN TRONG HOA DON KO DC PHEP AM

CREATE TRIGGER RANGBUOC_TONGTIEN_HDB
ON HOADONBAN
FOR INSERT, UPDATE
AS
	BEGIN
	IF(SELECT TONGTIEN FROM INSERTED)<0
		BEGIN
			PRINT N'TỔNG TIỀN PHẢI LỚN HƠN 0'
			ROLLBACK TRAN
		END
	END
GO

--RANG BUOC TONG TIEN HOA DON NHAP TRONG HOA DON KO DC PHEP AM

CREATE TRIGGER RANGBUOC_TONGTIEN_HDNHAP
ON PHIEUNHAP
FOR INSERT, UPDATE
AS
	BEGIN
	IF(SELECT TONGTIENNHAP FROM INSERTED)<0
		BEGIN
			PRINT N'TỔNG TIỀN KHÔNG ĐƯỢC NHỎ HƠN 0'
			ROLLBACK TRAN
		END
	END
GO

--RANG BUOC SO TIEN CON LAI HOA DON NHAP TRONG HOA DON KO DC PHEP AM

CREATE TRIGGER RANGBUOC_SOTIENCONLAI_HDNHAP
ON PHIEUNHAP
FOR INSERT, UPDATE
AS
	BEGIN
	IF(SELECT SOTIENCONLAI FROM INSERTED)<0
		BEGIN
			PRINT N'SỐ TIỀN KHÔNG ĐƯỢC NHỎ HƠN 0'
			ROLLBACK TRAN
		END
	END
GO

--TU THEM DON GIA TRONG CHITIETHD BAN KHI NHAP CHO
CREATE TRIGGER THEMGIAVAOCTHD_BAN
ON CHITIETHOADONBAN
FOR INSERT
AS
	DECLARE @DG MONEY
	SET @DG=(SELECT DONGIABAN FROM INSERTED, CHO WHERE INSERTED.MAXACNHAN=CHO.MAXACNHAN)
	UPDATE CHITIETHOADONBAN
	SET DONGIABAN=@DG
	WHERE CHITIETHOADONBAN.MAXACNHAN=(SELECT MAXACNHAN FROM INSERTED) AND CHITIETHOADONBAN.MAXACNHAN=(SELECT MAXACNHAN FROM INSERTED)
GO

--GIAM SO LUONG CHO

CREATE TRIGGER GIAMSLCHO
ON CHITIETHOADONBAN
FOR INSERT
AS
	BEGIN
		IF(SELECT SOLUONGBAN FROM CHO, LOAICHO, INSERTED WHERE INSERTED.MAXACNHAN=CHO.MAXACNHAN AND CHO.MALOAI=LOAICHO.MALOAI)=0
		BEGIN
			PRINT'HET HANG'
			ROLLBACK TRAN
		END
		ELSE
		BEGIN
			IF(SELECT SOLUONGBAN FROM INSERTED)>(SELECT SL FROM CHO, INSERTED, KHO WHERE KHO.MALOAI=CHO.MALOAI AND INSERTED.MAXACNHAN=CHO.MAXACNHAN)
			BEGIN
				PRINT N'KHONG DU HANG BAN'
				ROLLBACK TRAN
			END
			ELSE
			BEGIN
			UPDATE KHO
			SET SL=SL-(SELECT SOLUONGBAN FROM INSERTED)
			WHERE KHO.MALOAI=(SELECT CHO.MALOAI FROM CHO, INSERTED, KHO WHERE inserted.MAXACNHAN=CHO.MAXACNHAN AND CHO.MALOAI=KHO.MALOAI )
			END
		END
	END


--TANG SO LUONG SACH

CREATE TRIGGER TANGSLCHO
ON CHITIETPHIEUNHAP
FOR INSERT
AS
	BEGIN
		UPDATE KHO
			SET SL=SL+(SELECT SOLUONGSP FROM INSERTED)
			WHERE KHO.MALOAI=(SELECT CHO.MALOAI FROM CHO, INSERTED WHERE inserted.MAXACNHAN=CHO.MAXACNHAN AND KHO.MALOAI=CHO.MALOAI)
	END
GO

--TINH TONG TIEN HOA DON XUAT


CREATE TRIGGER TT_HD_XUAT
ON CHITIETHOADONBAN
FOR INSERT
AS
	BEGIN
		UPDATE HOADONBAN
		SET TONGTIEN=TONGTIEN+(SELECT SUM(SOLUONGBAN*DONGIABAN) FROM INSERTED WHERE INSERTED.MAHD=HOADONBAN.MAHD)
		WHERE HOADONBAN.MAHD=(SELECT MAHD FROM INSERTED)
	END
GO


--TINH TONG TIEN HOA DON NHAP

CREATE TRIGGER TT_HD_NHAP
ON CHITIETPHIEUNHAP
FOR INSERT, UPDATE,DELETE
AS
	BEGIN
		UPDATE PHIEUNHAP
		SET TONGTIENNHAP=(TONGTIENNHAP+(SELECT SUM(SOLUONGSP*GIATIEN) FROM INSERTED WHERE INSERTED.MAPN=PHIEUNHAP.MAPN))
		WHERE PHIEUNHAP.MAPN=(SELECT MAPN FROM INSERTED)

		UPDATE PHIEUNHAP
		SET SOTIENCONLAI=(TONGTIENNHAP+(SELECT SUM(SOLUONGSP*GIATIEN) FROM INSERTED WHERE INSERTED.MAPN=PHIEUNHAP.MAPN))-SOTIENTRATRUOC_NCC
		WHERE PHIEUNHAP.MAPN=(SELECT MAPN FROM INSERTED)
	END
GO

--TAO NHAN VIEN TU DONG THEM TAI KHOAN

CREATE TRIGGER NV_TK
ON NHANVIEN
FOR INSERT, DELETE
AS
	BEGIN
		INSERT INTO TAIKHOANNV(MANV)
			SELECT MATK=INSERTED.MANV FROM INSERTED
		INSERT INTO NHOMQUYEN(MANV, MAQUYEN)
			SELECT MATK=INSERTED.MANV, MAQUYEN='U001' FROM INSERTED
		DELETE NHOMQUYEN
		WHERE MANV=(SELECT MANV FROM DELETED)
		DELETE TAIKHOANNV
		WHERE MANV=(SELECT MANV FROM DELETED)
	END

--SO LUONG MUA CHO TRONG CHI TIET HOA DON XUAT LON HON 0

CREATE TRIGGER CTHD_CHO_XUAT
ON CHITIETHOADONBAN
FOR INSERT, UPDATE, DELETE
AS
	BEGIN
	IF(SELECT INSERTED.SOLUONGBAN FROM INSERTED)<0
		BEGIN
			PRINT N'SỐ LƯỢNG CHÓ PHẢI LỚN HƠN 0'
			ROLLBACK TRAN
		END
END

--SO LUONG NHAP CHO TRONG CHI TIET HOA DON NHAP LON HON 0


CREATE TRIGGER CTHD_CHO_NHAP
ON CHITIETPHIEUNHAP
FOR INSERT, UPDATE, DELETE
AS
	BEGIN
	IF(SELECT INSERTED.SOLUONGSP FROM INSERTED)<0
		BEGIN
			PRINT N'SỐ LƯỢNG PHẢI LỚN HƠN 0'
			ROLLBACK TRAN
		END
	END

--RANG BUOC SO LUONG CHO LON HON 0


CREATE TRIGGER SL_SACH
ON KHO
FOR INSERT,UPDATE
AS
	BEGIN 
	IF(SELECT SL FROM INSERTED)<0
		BEGIN
		PRINT N'SỐ LƯỢNG CHÓ KHÔNG NHỎ HƠN 0'
		ROLLBACK TRAN
		END
	END
--FUNCTION
--TAO MA HOA DON NHAP TU DONG

CREATE FUNCTION SINHMA_HOADONBAN()
RETURNS VARCHAR(30)
AS
	BEGIN
	DECLARE @MHD VARCHAR(100)
	SET @MHD='HDN'+CONVERT(NVARCHAR(10),MONTH(GETDATE()))+CONVERT(NVARCHAR(10),DAY(GETDATE()))+REPLACE(((CONVERT(NVARCHAR(10),(GETDATE()),108))),':','')
	RETURN @MHD
END
